apiVersion: batch/v1
kind: Job
metadata:
  name: bindicator-job
spec:
  template:
    spec:
      containers:
      - name: bindicator-job
        image: yash5090/bindicator:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
