apiVersion: apps/v1
kind: Deployment
metadata:
  name: bindicator-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: bindicator
  template:
    metadata:
      labels:
        app: bindicator
    spec:
      containers:
        - name: bindicator
          image: yash5090/bindicator:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
